Charging board respin
waterloo-rocketry/cansw_charging pull request #4
Opened 2024-04-09 03:26 UTC by AshTheEngiqueer

Airbrakes enable/disable has been written, and preprocessor instructions added to compile only the correct code for each board. Current sensing added for 13V, BATT, and MOTOR lines, and error checks written. Still on to-do list is implement correct motor control code (once drivers are written), and change the pinout to allow testing on keto board.

2024-04-10 11:55 UTC, Joe-Joe-Joe-Joe requested changes

2024-04-10 11:55 UTC, Joe-Joe-Joe-Joe commented on error_checks.h
> +#define 5V_OVERCURRENT_THRESHOLD_mA 3000 //buck rated for 3A max
If you are pushing 3A through a 3A buck by the time you see the error message something will have broken. This is why we have to estimate the bus current so we know how much is "too much" current. Also worth noting that the Geckos are only rated for (I think) 2A on a single pin. So thats also an issue.

2024-04-10 11:55 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    return (MIN_PULSE_WIDTH_US + percent(MAX_PULSE_WIDTH_US - MIN_PULSE_WIDTH_US));
this is going to give a compilation error, not multiply

2024-04-10 11:55 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    return (MIN_PULSE_WIDTH_US + percent(MAX_PULSE_WIDTH_US - MIN_PULSE_WIDTH_US));
Also if you use a percentage you need to mention somewhere whether that's 0-1 or 0-100. I realize in this case I just told you how to interpret it, but rando person doesn't know that

2024-04-10 11:55 UTC, Joe-Joe-Joe-Joe commented on main.c
> +bool debug_en = false;
You _may_ need `volatile` on some of these variables.

2024-06-01 14:51 UTC, Joe-Joe-Joe-Joe requested changes

2024-06-01 14:51 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    uint32_t pulseWidth_us = (uint32_t) (MOTOR_MIN_PULSE_WIDTH_US + ((1-percent)*0.65) * (MOTOR_MAX_PULSE_WIDTH_US - MOTOR_MIN_PULSE_WIDTH_US));
Rather than scaling it here, please scale it using the min/max degrees defined at the top of the file. Doing the inversion here I think is fine

2024-07-04 22:09 UTC, Lucifersan commented
there are a few things that should be changed in the future but I believe this suffices currently

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe requested changes
I think we could probably drop the ifdefs from error checks completely, and only use them to control which functions are actually called in main. We are not that constrained on program memory where we need to worry about this

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on error_checks.c
> +    uint16_t adc_result = ADCC_GetSingleConversion(channel_BATT_VOLT);
this was used for testing purposes. not that the compiler cares but can we put it back into one line?

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on error_checks.h
> +#define OVERCURRENT_THRESHOLD_5V_mA 1900 //buck rated for 2A max
I would cut this down to 85%-90%. These will change anyway once we do the rocket load test I want to do.

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +//const uint32_t BOOST_LENGTH_MS = 15000; // 15000ms = 15s - CHANGE THIS
remove these

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +//Commanded extension is 0-1 as fraction of full extension
update all this to new format

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +const uint32_t MOTOR_ACT_TIME_MS = 5000; //Motor guaranteed to fully actuate in this time
this is horribly conservative. 500 ms is more accurate

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +const uint16_t MOTOR_MAX_PULSE_WIDTH_US = 2500; // corresponds to 180 deg
comment is no longer true. 2500us now corresponds to 117 deg

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +const uint16_t AB_MIN_EXT_DEG = 0; //under this the servo will stall - 20 deg
we can now scrap these cause the servo itself is constrained on actuation angle

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +#define PERCENT_TO_DEG(percent) ( (float) percent * (AB_MAX_EXT_DEG - AB_MIN_EXT_DEG) + AB_MIN_EXT_DEG)
update for new message format

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    #if (BOARD_UNIQUE_ID != BOARD_ID_CHARGING_CAN)
I would use a || here

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    //BATTERY_CHARGER_EN(true);
remove errant comment

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +            BLUE_LED_SET(MOTOR_POWER == MOTOR_ON);
is this used only on motor control copies?

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    //echo -n "m0C0,00,00,00,01,00;" > /dev/tty.usbmodem12401                   //injector valve open message
delete

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +    if (get_board_unique_id(msg) == BOARD_UNIQUE_ID || get_board_unique_id(msg)==BOARD_ID_LOGGER) {
why are we randomly ignoring logger board messages???

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +                    BLUE_LED_SET(true); //temporarily commented out
what does the comment mean? is this meant to be here or not?

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +                    BLUE_LED_SET(true); //temporarily commented out
I'm assuming no since it has overlap with the motor power implementation in the main loop?

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +            float act_state = get_req_actuator_state_analog(msg);
rewrite all this for format change

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on main.c
> +void pwm_init(void){
I would put this in a different source file for cleanliness, and also cut out the test lines. The steps from the datasheet are good and you should keep them

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on mcc_generated_files/adcc.c
> +    ADPCH = 0b010100;//x00;
what does this do?

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on platform.h
> +// Voltage monitoring in 47k Ohms
that's a weird choice of units

2024-07-05 19:11 UTC, Joe-Joe-Joe-Joe commented on rocketlib
Do we still use anything from rocketlib? if not, best remove it completely

2024-07-05 21:48 UTC, AshTheEngiqueer commented on mcc_generated_files/adcc.c
> +    ADPCH = 0b010100;//x00;
sets positive ADC input channel to ANC4

2024-07-06 01:21 UTC, Joe-Joe-Joe-Joe commented
Are you confident that building without any of the valid board IDs doesn't lead to unexpected behaviour? if not, you should add a `#error` if a valid board ID is not defined

2024-07-09 13:51 UTC, Joe-Joe-Joe-Joe approved these changes
I am assuming this version has been tested on hardware

2024-07-09 14:22 UTC, merged